### ISSUE TITLE
500 error on authorization

### ISSUE THREAD

**Issue by shermandy** [NeoCat/Arduno-Twitter-library#4]
My arduino project that used this library stopped working earlier this month. I de-authorized the library from my Twitter account and when I tried to reauthorize it, I receive a 500 error. It seems that the website behind this is no longer functioning. Can this be confirmed?

**Comment by NeoCat** [comment]
The backend server used in v1.3.0 had been shutdown due to a budget problem caused by too many strange requests.  I have moved it to another server and released the library v1.3.1. Please update and re-authorize.

**Comment by shermandy** [comment]
Thank you! The new server works as expected and my project is functional again! It's amazing that you're still supporting this project after so many years.
